/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BillingInfoVerification struct {
	VerificationAmount float32 `json:"verificationAmount,omitempty"`
	Id int32 `json:"id"`
	ProvisionOrderId int32 `json:"provisionOrderId,omitempty"`
}
