/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ARecordReturn struct {
	Address string `json:"address,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Ttl int32 `json:"ttl"`
	DomainId int32 `json:"domainId"`
	Type_ string `json:"type"`
}
