/*
 * Hivelocity API for Partners
 *
 * Interact with Hivelocity
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Location struct {
	Location *CityStateCountry `json:"location,omitempty"`
	Edge bool `json:"edge,omitempty"`
	Core bool `json:"core,omitempty"`
	Code string `json:"code,omitempty"`
}
